var createBuLangModule=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var h=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,l=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,ca="./this.program",n=(a,b)=>{throw b;};"undefined"!=typeof __filename?_scriptName=__filename:ba&&(_scriptName=self.location.href);var da="",ea,fa;
if(l){var fs=require("fs");da=__dirname+"/";fa=a=>{a=ha(a)?new URL(a):a;return fs.readFileSync(a)};ea=async a=>{a=ha(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);n=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{da=(new URL(".",_scriptName)).href}catch{}ba&&(fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ea=async a=>{if(ha(a))return new Promise((c,
d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ia=console.log.bind(console),r=console.error.bind(console),x,ja=!1,ka,ha=a=>a.startsWith("file://"),la,ma,y,B,na,C,E,F,oa,pa,qa,ra,sa=!1;
function ta(){var a=ua.buffer;y=new Int8Array(a);na=new Int16Array(a);B=new Uint8Array(a);C=new Uint16Array(a);E=new Int32Array(a);F=new Uint32Array(a);oa=new Float32Array(a);pa=new Float64Array(a);qa=new BigInt64Array(a);ra=new BigUint64Array(a)}function va(a){h.onAbort?.(a);a="Aborted("+a+")";r(a);ja=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ma?.(a);throw a;}var wa;
async function xa(a){if(!x)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==wa&&x)a=new Uint8Array(x);else if(fa)a=fa(a);else throw"both async and sync fetching of the wasm failed";return a}async function ya(a,b){try{var c=await xa(a);return await WebAssembly.instantiate(c,b)}catch(d){r(`failed to asynchronously prepare wasm: ${d}`),va(d)}}
async function za(a){var b=wa;if(!x&&!ha(b)&&!l)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){r(`wasm streaming compile failed: ${d}`),r("falling back to ArrayBuffer instantiation")}return ya(b,a)}class Aa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Ba=a=>{for(;0<a.length;)a.shift()(h)},Ca=[],Da=[],Ea=()=>{var a=h.preRun.shift();Da.push(a)},Fa=!0;
class Ga{constructor(a){this.da=a-24}}var Ha=0,Ia=0,G=a=>{for(var b="";;){var c=B[a++];if(!c)return b;b+=String.fromCharCode(c)}},H={},I={},Ja={},J=class extends Error{constructor(a){super(a);this.name="BindingError"}},La=a=>{throw new J(a);};
function Ma(a,b,c={}){var d=b.name;if(!a)throw new J(`type "${d}" must have a positive integer typeid pointer`);if(I.hasOwnProperty(a)){if(c.qa)return;throw new J(`Cannot register type '${d}' twice`);}I[a]=b;delete Ja[a];H.hasOwnProperty(a)&&(b=H[a],delete H[a],b.forEach(e=>e()))}function L(a,b,c={}){return Ma(a,b,c)}
var Na=(a,b,c)=>{switch(b){case 1:return c?d=>y[d]:d=>B[d];case 2:return c?d=>na[d>>1]:d=>C[d>>1];case 4:return c?d=>E[d>>2]:d=>F[d>>2];case 8:return c?d=>qa[d>>3]:d=>ra[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Oa=[],M=[0,1,,1,null,1,!0,1,!1,1],Pa=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Oa.pop()||M.length;M[b]=a;M[b+1]=1;return b}};function Qa(a){return this.M(F[a>>2])}
var Ra={name:"emscripten::val",M:a=>{if(!a)throw new J(`Cannot use deleted val. handle = ${a}`);var b=M[a];9<a&&0===--M[a+1]&&(M[a]=void 0,Oa.push(a));return b},U:(a,b)=>Pa(b),W:Qa,O:null},Sa=(a,b)=>{switch(b){case 4:return function(c){return this.M(oa[c>>2])};case 8:return function(c){return this.M(pa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ta=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Ua(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].O)return!0;return!1}
var Va=(a,b)=>{if(void 0===h[a].N){var c=h[a];h[a]=function(...d){if(!h[a].N.hasOwnProperty(d.length))throw new J(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${h[a].N})!`);return h[a].N[d.length].apply(this,d)};h[a].N=[];h[a].N[c.ja]=c}},Wa=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].N&&void 0!==h[a].N[c])throw new J(`Cannot register public name '${a}' twice`);Va(a,a);if(h[a].N.hasOwnProperty(c))throw new J(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].N[c]=b}else h[a]=b,h[a].ja=c},Xa=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(F[b+4*d>>2]);return c},Ya=class extends Error{constructor(a){super(a);this.name="InternalError"}},Za=[],ab=(a,b)=>{a=G(a);var c;(c=Za[b])||(Za[b]=c=$a.get(b));if("function"!=typeof c)throw new J(`unknown function pointer with signature ${a}: ${b}`);return c};class bb extends Error{}
var db=a=>{a=cb(a);var b=G(a);N(a);return b},eb=(a,b)=>{function c(f){e[f]||I[f]||(Ja[f]?Ja[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new bb(`${a}: `+d.map(db).join([", "]));},fb=(a,b)=>{function c(k){k=b(k);if(k.length!==d.length)throw new Ya("Mismatched type converter count");for(var p=0;p<d.length;++p)L(d[p],k[p])}var d=[];d.forEach(k=>Ja[k]=a);var e=Array(a.length),f=[],g=0;for(let [k,p]of a.entries())I.hasOwnProperty(p)?e[k]=I[p]:(f.push(p),H.hasOwnProperty(p)||(H[p]=
[]),H[p].push(()=>{e[k]=I[p];++g;g===f.length&&c(e)}));0===f.length&&c(e)},gb=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},O=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>
6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},hb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},ib=globalThis.TextDecoder&&new TextDecoder,jb=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},P=(a,b=0,c,d)=>{c=jb(a,b,c,d);if(16<c-b&&a.buffer&&ib)return ib.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;
e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},kb=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,lb=(a,b,c)=>{a>>=1;b=jb(C,a,b/2,c);if(16<b-a&&kb)return kb.decode(C.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(C[a]);return c},mb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)na[b>>
1]=a.charCodeAt(e),b+=2;na[b>>1]=0;return b-d},nb=a=>2*a.length,ob=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=F[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},pb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d},qb=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},rb=0,sb=[0,31,60,91,121,152,182,213,244,274,305,335],tb=[0,
31,59,90,120,151,181,212,243,273,304,334],Q={},ub=a=>{ka=a;Fa||0<rb||(h.onExit?.(a),ja=!0);n(a,new Aa(a))},vb=a=>{if(!ja)try{if(a(),!(Fa||0<rb))try{ka=a=ka,ub(a)}catch(b){b instanceof Aa||"unwind"==b||n(1,b)}}catch(b){b instanceof Aa||"unwind"==b||n(1,b)}},wb={},Ab=()=>{if(!zb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in wb)void 0===wb[b]?delete a[b]:a[b]=wb[b];
var c=[];for(b in a)c.push(`${b}=${a[b]}`);zb=c}return zb},zb,Bb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Cb=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Bb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Db=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";
b&&=b.slice(0,-1);return a+b},Eb=()=>{if(l){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Fb=a=>{(Fb=Eb())(a)},Gb=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Bb(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Hb=[],Ib=[];
function Jb(a,b){Ib[a]={input:[],output:[],Z:b};Kb(a,Lb)}
var Lb={open(a){var b=Ib[a.node.rdev];if(!b)throw new R(43);a.tty=b;a.seekable=!1},close(a){a.tty.Z.fsync(a.tty)},fsync(a){a.tty.Z.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Z.la)throw new R(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Z.la(a.tty)}catch(k){throw new R(29);}if(void 0===g&&0===e)throw new R(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Z.ia)throw new R(60);try{for(var e=0;e<d;e++)a.tty.Z.ia(a.tty,b[c+e])}catch(f){throw new R(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Mb={la(){a:{if(!Hb.length){var a=null;if(l){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(hb(a)+1);a=O(a,b,0,b.length);b.length=a;Hb=b}a=Hb.shift()}return a},ia(a,b){null===b||10===b?(ia(P(a.output)),a.output=
[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ia(P(a.output)),a.output=[])},Da(){return{ya:25856,Aa:5,xa:191,za:35387,wa:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ea(){return 0},Fa(){return[24,80]}},Nb={ia(a,b){null===b||10===b?(r(P(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(r(P(a.output)),a.output=[])}},S={R:null,T(){return S.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new R(63);
S.R||(S.R={dir:{node:{V:S.J.V,S:S.J.S,lookup:S.J.lookup,aa:S.J.aa,rename:S.J.rename,unlink:S.J.unlink,rmdir:S.J.rmdir,readdir:S.J.readdir,symlink:S.J.symlink},stream:{P:S.K.P}},file:{node:{V:S.J.V,S:S.J.S},stream:{P:S.K.P,read:S.K.read,write:S.K.write,na:S.K.na,pa:S.K.pa}},link:{node:{V:S.J.V,S:S.J.S,readlink:S.J.readlink},stream:{}},ka:{node:{V:S.J.V,S:S.J.S},stream:Ob}});c=Pb(a,b,c,d);16384===(c.mode&61440)?(c.J=S.R.dir.node,c.K=S.R.dir.stream,c.I={}):32768===(c.mode&61440)?(c.J=S.R.file.node,c.K=
S.R.file.stream,c.L=0,c.I=null):40960===(c.mode&61440)?(c.J=S.R.link.node,c.K=S.R.link.stream):8192===(c.mode&61440)&&(c.J=S.R.ka.node,c.K=S.R.ka.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.I[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Ca(a){return a.I?a.I.subarray?a.I.subarray(0,a.L):new Uint8Array(a.I):new Uint8Array(0)},J:{V(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&
61440)?b.size=a.L:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},S(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.L!=b&&(0==b?(a.I=null,a.L=0):(c=a.I,a.I=new Uint8Array(b),c&&a.I.set(c.subarray(0,Math.min(b,a.L))),a.L=b)))},lookup(){S.ea||(S.ea=new R(44),S.ea.stack="<generic error, no stack>");throw S.ea;
},aa(a,b,c,d){return S.createNode(a,b,c,d)},rename(a,b,c){try{var d=Qb(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.I)throw new R(55);e=Rb(d.parent.id,d.name);if(T[e]===d)T[e]=d.Y;else for(e=T[e];e;){if(e.Y===d){e.Y=d.Y;break}e=e.Y}}delete a.parent.I[a.name];b.I[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.I[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=Qb(a,b),d;for(d in c.I)throw new R(55);delete a.I[b];a.ctime=a.mtime=Date.now()},
readdir(a){return[".","..",...Object.keys(a.I)]},symlink(a,b,c){a=S.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new R(28);return a.link}},K:{read(a,b,c,d,e){var f=a.node.I;if(e>=a.node.L)return 0;a=Math.min(a.node.L-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===y.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.I||a.I.subarray)){if(f)return a.I=
b.subarray(c,c+d),a.L=d;if(0===a.L&&0===e)return a.I=b.slice(c,c+d),a.L=d;if(e+d<=a.L)return a.I.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.I?a.I.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.I,a.I=new Uint8Array(f),0<a.L&&a.I.set(g.subarray(0,a.L),0));if(a.I.subarray&&b.subarray)a.I.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.I[e+f]=b[c+f];a.L=Math.max(a.L,e+d);return d},P(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.L);if(0>
b)throw new R(28);return b},na(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new R(43);a=a.node.I;if(e&2||!a||a.buffer!==y.buffer){d=!0;va();e=void 0;if(!e)throw new R(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);y.set(a,e)}}else d=!1,e=a.byteOffset;return{da:e,va:d}},pa(a,b,c,d){S.K.write(a,b,0,d,c,!1);return 0}}},Sb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Tb=null,Ub={},U=[],Vb=1,T=null,Wb=!1,Xb=!0,Yb={},R=class{name="ErrnoError";constructor(a){this.X=
a}},Zb=class{$={};node=null;get flags(){return this.$.flags}set flags(a){this.$.flags=a}get position(){return this.$.position}set position(a){this.$.position=a}},$b=class{J={};K={};ba=null;constructor(a,b,c,d){a||=this;this.parent=a;this.T=a.T;this.id=Vb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=
-147}};
function V(a,b={}){if(!a)throw new R(44);b.ga??(b.ga=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=Tb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Db(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Cb(e+"/"+a[f]);try{d=Qb(d,a[f])}catch(k){if(44===k?.X&&g&&b.ta)return{path:e};throw k;}!d.ba||g&&!b.ga||(d=d.ba.root);if(40960===(d.mode&61440)&&(!g||b.fa)){if(!d.J.readlink)throw new R(52);
d=d.J.readlink(d);"/"===d.charAt(0)||(d=Db(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new R(32);}function Rb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%T.length}function Qb(a,b){var c=16384===(a.mode&61440)?(c=ac(a,"x"))?c:a.J.lookup?0:2:54;if(c)throw new R(c);for(c=T[Rb(a.id,b)];c;c=c.Y){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.J.lookup(a,b)}
function Pb(a,b,c,d){a=new $b(a,b,c,d);b=Rb(a.parent.id,a.name);a.Y=T[b];return T[b]=a}function bc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function ac(a,b){if(Xb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function cc(a,b){if(16384!==(a.mode&61440))return 54;try{return Qb(a,b),20}catch(c){}return ac(a,"wx")}function W(a){a=U[a];if(!a)throw new R(8);return a}
function dc(a,b){var c=null?.K.S,d=c?null:a;c??=a.J.S;if(!c)throw new R(63);c(d,b)}var Ob={open(a){a.K=Ub[a.node.rdev].K;a.K.open?.(a)},P(){throw new R(70);}};function Kb(a,b){Ub[a]={K:b}}function ec(a,b){var c="/"===b;if(c&&Tb)throw new R(10);if(!c&&b){var d=V(b,{ga:!1});b=d.path;d=d.node;if(d.ba)throw new R(10);if(16384!==(d.mode&61440))throw new R(54);}b={type:a,Ga:{},oa:b,sa:[]};a=a.T(b);a.T=b;b.root=a;c?Tb=a:d&&(d.ba=b,d.T&&d.T.sa.push(b))}
function fc(a,b,c){var d=V(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new R(28);if("."===a||".."===a)throw new R(20);var e=cc(d,a);if(e)throw new R(e);if(!d.J.aa)throw new R(63);return d.J.aa(d,a,b,c)}function X(a){return fc(a,16895,0)}function gc(a,b,c){"undefined"==typeof c&&(c=b,b=438);fc(a,b|8192,c)}
function hc(a,b){if(!Gb(a))throw new R(44);var c=V(b,{parent:!0}).node;if(!c)throw new R(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=cc(c,b);if(d)throw new R(d);if(!c.J.symlink)throw new R(63);c.J.symlink(c,b,a)}
function ic(a,b){if(""===a)throw new R(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}c=b&64?33206:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");a=V(a,{fa:!(b&131072),ta:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new R(20);}else{if(e)throw new R(31);d=fc(a,c|511,0);f=!0}if(!d)throw new R(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&61440))throw new R(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==bc(b)||b&576)?31:ac(d,bc(b)):44))throw new R(e);if(b&512&&!f){e=d;e="string"==typeof e?V(e,{fa:!0}).node:e;if(16384===(e.mode&61440))throw new R(31);if(32768!==(e.mode&61440))throw new R(28);var g=ac(e,"w");if(g)throw new R(g);dc(e,{size:0,timestamp:Date.now()})}b&=-131713;a:for(e=d;;){if(e===e.parent){e=e.T.oa;var k=k?"/"!==e[e.length-1]?`${e}/${k}`:e+k:e;break a}k=k?`${e.name}/${k}`:e.name;e=e.parent}k={node:d,path:k,flags:b,seekable:!0,
position:0,K:d.K,ua:[],error:!1};e=-1;k=Object.assign(new Zb,k);if(-1==e)a:{for(e=0;4096>=e;e++)if(!U[e])break a;throw new R(33);}k.fd=e;U[e]=k;k.K.open&&k.K.open(k);f&&(c&=511,d="string"==typeof d?V(d,{fa:!0}).node:d,dc(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),Ba:void 0}));!h.logReadFiles||b&1||a in Yb||(Yb[a]=1)}function jc(a,b,c){if(null===a.fd)throw new R(8);if(!a.seekable||!a.K.P)throw new R(70);if(0!=c&&1!=c&&2!=c)throw new R(28);a.position=a.K.P(a,b,c);a.ua=[]}
function Y(a,b,c){a=Cb("/dev/"+a);var d=Sb(!!b,!!c);Y.ma??(Y.ma=64);var e=Y.ma++<<8|0;Kb(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,k,p){for(var m=0,z=0;z<p;z++){try{var w=b()}catch(q){throw new R(29);}if(void 0===w&&0===m)throw new R(6);if(null===w||void 0===w)break;m++;g[k+z]=w}m&&(f.node.atime=Date.now());return m},write(f,g,k,p){for(var m=0;m<p;m++)try{c(g[k+m])}catch(z){throw new R(29);}p&&(f.node.mtime=f.node.ctime=Date.now());return m}});gc(a,d,e)}var Z={};T=Array(4096);
ec(S,"/");X("/tmp");X("/home");X("/home/web_user");(function(){X("/dev");Kb(259,{read:()=>0,write:(d,e,f,g)=>g,P:()=>0});gc("/dev/null",259);Jb(1280,Mb);Jb(1536,Nb);gc("/dev/tty",1280);gc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Fb(a),b=a.byteLength);return a[--b]};Y("random",c);Y("urandom",c);X("/dev/shm");X("/dev/shm/tmp")})();
(function(){X("/proc");var a=X("/proc/self");X("/proc/self/fd");ec({T(){var b=Pb(a,"fd",16895,73);b.K={P:S.K.P};b.J={lookup(c,d){c=+d;var e=W(c);c={parent:null,T:{oa:"fake"},J:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(U.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.noExitRuntime&&(Fa=h.noExitRuntime);h.print&&(ia=h.print);h.printErr&&(r=h.printErr);h.wasmBinary&&(x=h.wasmBinary);h.thisProgram&&(ca=h.thisProgram);
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();
var kc,N,cb,lc,ua,$a,mc={d:(a,b,c)=>{var d=new Ga(a);F[d.da+16>>2]=0;F[d.da+4>>2]=b;F[d.da+8>>2]=c;Ha=a;Ia++;throw Ha;},q:()=>va(""),f:(a,b,c,d,e)=>{b=G(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=k=>BigInt.asUintN(g,k);e=f(e)}L(a,{name:b,M:f,U:(g,k)=>{"number"==typeof k&&(k=BigInt(k));return k},W:Na(b,c,!d),O:null})},j:(a,b,c,d)=>{b=G(b);L(a,{name:b,M:function(e){return!!e},U:function(e,f){return f?c:d},W:function(e){return this.M(B[e])},O:null})},h:a=>L(a,Ra),e:(a,b,c)=>{b=G(b);L(a,{name:b,M:d=>
d,U:(d,e)=>e,W:Sa(b,c),O:null})},g:(a,b,c,d,e,f,g)=>{var k=Xa(b,c);a=G(a);a=gb(a);e=ab(d,e);Wa(a,function(){eb(`Cannot call ${a} due to unbound types`,k)},b-1);fb(k,p=>{var m=[p[0],null].concat(p.slice(1));p=a;var z=a;var w=e,q=m.length;if(2>q)throw new J("argTypes array size mismatch! Must at least get return value and 'this' types!");var A=null!==m[1]&&!1,D=Ua(m),K=!m[0].ra,t=m[0],v=m[1];w=[z,La,w,f,Ta,t.M.bind(t),v?.U.bind(v)];for(t=2;t<q;++t)v=m[t],w.push(v.U.bind(v));if(!D)for(t=A?1:2;t<m.length;++t)null!==
m[t].O&&w.push(m[t].O);D=Ua(m);t=m.length-2;var u=[];v=["fn"];A&&v.push("thisWired");for(q=0;q<t;++q)u.push(`arg${q}`),v.push(`arg${q}Wired`);u=u.join(",");v=v.join(",");u=`return function (${u}) {\n`;D&&(u+="var destructors = [];\n");var xb=D?"destructors":"null",Ka="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");A&&(u+=`var thisWired = toClassParamWire(${xb}, this);\n`);for(q=0;q<t;++q){var yb=`toArg${q}Wire`;u+=`var arg${q}Wired = ${yb}(${xb}, arg${q});\n`;
Ka.push(yb)}u+=(K||g?"var rv = ":"")+`invoker(${v});\n`;if(D)u+="runDestructors(destructors);\n";else for(q=A?1:2;q<m.length;++q)A=1===q?"thisWired":"arg"+(q-2)+"Wired",null!==m[q].O&&(u+=`${A}_dtor(${A});\n`,Ka.push(`${A}_dtor`));K&&(u+="var ret = fromRetWire(rv);\nreturn ret;\n");m=(new Function(Ka,u+"}\n"))(...w);z=Object.defineProperty(m,"name",{value:z});m=b-1;if(!h.hasOwnProperty(p))throw new Ya("Replacing nonexistent public symbol");void 0!==h[p].N&&void 0!==m?h[p].N[m]=z:(h[p]=z,h[p].ja=m);
return[]})},b:(a,b,c,d,e)=>{b=G(b);let f=k=>k;if(0===d){var g=32-8*c;f=k=>k<<g>>>g;e=f(e)}L(a,{name:b,M:f,U:(k,p)=>p,W:Na(b,c,0!==d),O:null})},a:(a,b,c)=>{function d(f){return new e(y.buffer,F[f+4>>2],F[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=G(c);L(a,{name:c,M:d,W:d},{qa:!0})},i:(a,b)=>{b=G(b);L(a,{name:b,M(c){var d=(d=c+4)?P(B,d,F[c>>2],!0):"";N(c);return d},U(c,d){d instanceof ArrayBuffer&&(d=
new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new J("Cannot pass non-string to std::string");var f=e?hb(d):d.length;var g=kc(4+f+1),k=g+4;F[g>>2]=f;e?O(d,B,k,f+1):B.set(d,k);null!==c&&c.push(N,g);return g},W:Qa,O(c){N(c)}})},c:(a,b,c)=>{c=G(c);if(2===b){var d=lb;var e=mb;var f=nb}else d=ob,e=pb,f=qb;L(a,{name:c,M:g=>{var k=d(g+4,F[g>>2]*b,!0);N(g);return k},U:(g,k)=>{if("string"!=typeof k)throw new J(`Cannot pass non-string to C++ string type ${c}`);
var p=f(k),m=kc(4+p+b);F[m>>2]=p/b;e(k,m+4,p+b);null!==g&&g.push(N,m);return m},W:Qa,O(g){N(g)}})},r:(a,b)=>{b=G(b);L(a,{ra:!0,name:b,M:()=>{},U:()=>{}})},l:()=>{Fa=!1;rb=0},t:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);E[b>>2]=a.getSeconds();E[b+4>>2]=a.getMinutes();E[b+8>>2]=a.getHours();E[b+12>>2]=a.getDate();E[b+16>>2]=a.getMonth();E[b+20>>2]=a.getFullYear()-1900;E[b+24>>2]=a.getDay();var c=a.getFullYear();E[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?tb:
sb)[a.getMonth()]+a.getDate()-1|0;E[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();E[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},m:(a,b)=>{Q[a]&&(clearTimeout(Q[a].id),delete Q[a]);if(!b)return 0;var c=setTimeout(()=>{delete Q[a];vb(()=>lc(a,performance.now()))},b);Q[a]={id:c,Ha:b};return 0},u:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,
6,1)).getTimezoneOffset();F[a>>2]=60*Math.max(f,e);E[b>>2]=Number(f!=e);b=g=>{var k=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(O(a,B,c,17),O(b,B,d,17)):(O(a,B,d,17),O(b,B,c,17))},A:function(a,b,c){if(!(0<=a&&3>=a))return 28;qa[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},z:()=>Date.now(),s:a=>{var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/
c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ua.buffer.byteLength+65535)/65536|0;try{ua.grow(d);ta();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},o:(a,b)=>{var c=0,d=0,e;for(e of Ab()){var f=b+c;F[a+d>>2]=f;c+=O(e,B,f,Infinity)+1;d+=4}return 0},p:(a,b)=>{var c=Ab();F[a>>2]=c.length;a=0;for(var d of c)a+=hb(d)+1;F[b>>2]=a;return 0},w:function(a){try{var b=W(a);if(null===b.fd)throw new R(8);b.ha&&(b.ha=null);try{b.K.close&&b.K.close(b)}catch(c){throw c;
}finally{U[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof Z||"ErrnoError"!==c.name)throw c;return c.X}},y:function(a,b,c,d){try{a:{var e=W(a);a=b;for(var f,g=b=0;g<c;g++){var k=F[a>>2],p=F[a+4>>2];a+=8;var m=e,z=k,w=p,q=f,A=y;if(0>w||0>q)throw new R(28);if(null===m.fd)throw new R(8);if(1===(m.flags&2097155))throw new R(8);if(16384===(m.node.mode&61440))throw new R(31);if(!m.K.read)throw new R(28);var D="undefined"!=typeof q;if(!D)q=m.position;else if(!m.seekable)throw new R(70);var K=
m.K.read(m,A,z,w,q);D||(m.position+=K);var t=K;if(0>t){var v=-1;break a}b+=t;if(t<p)break;"undefined"!=typeof f&&(f+=t)}v=b}F[d>>2]=v;return 0}catch(u){if("undefined"==typeof Z||"ErrnoError"!==u.name)throw u;return u.X}},v:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=W(a);jc(e,b,c);qa[d>>3]=BigInt(e.position);e.ha&&0===b&&0===c&&(e.ha=null);return 0}catch(f){if("undefined"==typeof Z||"ErrnoError"!==f.name)throw f;return f.X}},x:function(a,
b,c,d){try{a:{var e=W(a);a=b;for(var f,g=b=0;g<c;g++){var k=F[a>>2],p=F[a+4>>2];a+=8;var m=e,z=k,w=p,q=f,A=y;if(0>w||0>q)throw new R(28);if(null===m.fd)throw new R(8);if(0===(m.flags&2097155))throw new R(8);if(16384===(m.node.mode&61440))throw new R(31);if(!m.K.write)throw new R(28);m.seekable&&m.flags&1024&&jc(m,0,2);var D="undefined"!=typeof q;if(!D)q=m.position;else if(!m.seekable)throw new R(70);var K=m.K.write(m,A,z,w,q,void 0);D||(m.position+=K);var t=K;if(0>t){var v=-1;break a}b+=t;if(t<p)break;
"undefined"!=typeof f&&(f+=t)}v=b}F[d>>2]=v;return 0}catch(u){if("undefined"==typeof Z||"ErrnoError"!==u.name)throw u;return u.X}},k:ub,n:function(a,b){try{return Fb(B.subarray(a,a+b)),0}catch(c){if("undefined"==typeof Z||"ErrnoError"!==c.name)throw c;return c.X}}},nc;
nc=await (async function(){function a(c){c=nc=c.exports;kc=c.D;N=c.E;cb=c.F;lc=c.H;ua=c.B;$a=c.G;ta();return nc}var b={a:mc};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});wa??=h.locateFile?h.locateFile("bulang.wasm",da):da+"bulang.wasm";return a((await za(b)).instance)}());
(function(){function a(){h.calledRun=!0;if(!ja){sa=!0;if(!h.noFSInit&&!Wb){var b,c;Wb=!0;b??=h.stdin;c??=h.stdout;d??=h.stderr;b?Y("stdin",b):hc("/dev/tty","/dev/stdin");c?Y("stdout",null,c):hc("/dev/tty","/dev/stdout");d?Y("stderr",null,d):hc("/dev/tty1","/dev/stderr");ic("/dev/stdin",0);ic("/dev/stdout",1);ic("/dev/stderr",1)}nc.C();Xb=!1;la?.(h);h.onRuntimeInitialized?.();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var d=h.postRun.shift();Ca.push(d)}Ba(Ca)}}
if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ea();Ba(Da);h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);a()},1)):a()})();sa?moduleRtn=h:moduleRtn=new Promise((a,b)=>{la=a;ma=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=createBuLangModule;module.exports.default=createBuLangModule}else if(typeof define==="function"&&define["amd"])define([],()=>createBuLangModule);
