var createBuLangModule=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var h=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,l=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,ca="./this.program",da=(a,b)=>{throw b;};"undefined"!=typeof __filename?_scriptName=__filename:ba&&(_scriptName=self.location.href);var ea="",fa,ha;
if(l){var fs=require("fs");ea=__dirname+"/";ha=a=>{a=ia(a)?new URL(a):a;return fs.readFileSync(a)};fa=async a=>{a=ia(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);da=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ea=(new URL(".",_scriptName)).href}catch{}ba&&(ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});fa=async a=>{if(ia(a))return new Promise((c,
d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ja=console.log.bind(console),n=console.error.bind(console),p,ka=!1,la,ia=a=>a.startsWith("file://"),ma,na,t,u,oa,y,C,D,pa,qa,ra,sa,ta=!1;
function ua(){var a=va.buffer;t=new Int8Array(a);oa=new Int16Array(a);u=new Uint8Array(a);y=new Uint16Array(a);C=new Int32Array(a);D=new Uint32Array(a);pa=new Float32Array(a);qa=new Float64Array(a);ra=new BigInt64Array(a);sa=new BigUint64Array(a)}function wa(a){h.onAbort?.(a);a="Aborted("+a+")";n(a);ka=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");na?.(a);throw a;}var xa;
async function ya(a){if(!p)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==xa&&p)a=new Uint8Array(p);else if(ha)a=ha(a);else throw"both async and sync fetching of the wasm failed";return a}async function za(a,b){try{var c=await ya(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),wa(d)}}
async function Aa(a){var b=xa;if(!p&&!ia(b)&&!l)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return za(b,a)}class Ba{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Ca=a=>{for(;0<a.length;)a.shift()(h)},Da=[],Ea=[],Fa=()=>{var a=h.preRun.shift();Ea.push(a)},Ga=!0;
class Ha{constructor(a){this.ia=a-24}}var Ia=0,Ja=0,F=a=>{for(var b="";;){var c=u[a++];if(!c)return b;b+=String.fromCharCode(c)}},G={},H={},Ka={},I=class extends Error{constructor(a){super(a);this.name="BindingError"}},Ma=a=>{throw new I(a);};
function Na(a,b,c={}){var d=b.name;if(!a)throw new I(`type "${d}" must have a positive integer typeid pointer`);if(H.hasOwnProperty(a)){if(c.va)return;throw new I(`Cannot register type '${d}' twice`);}H[a]=b;delete Ka[a];G.hasOwnProperty(a)&&(b=G[a],delete G[a],b.forEach(e=>e()))}function J(a,b,c={}){return Na(a,b,c)}
var Oa=(a,b,c)=>{switch(b){case 1:return c?d=>t[d]:d=>u[d];case 2:return c?d=>oa[d>>1]:d=>y[d>>1];case 4:return c?d=>C[d>>2]:d=>D[d>>2];case 8:return c?d=>ra[d>>3]:d=>sa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Pa=[],K=[0,1,,1,null,1,!0,1,!1,1],Qa=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Pa.pop()||K.length;K[b]=a;K[b+1]=1;return b}};function Ra(a){return this.S(D[a>>2])}
var Sa={name:"emscripten::val",S:a=>{if(!a)throw new I(`Cannot use deleted val. handle = ${a}`);var b=K[a];9<a&&0===--K[a+1]&&(K[a]=void 0,Pa.push(a));return b},Z:(a,b)=>Qa(b),aa:Ra,U:null},Ta=(a,b)=>{switch(b){case 4:return function(c){return this.S(pa[c>>2])};case 8:return function(c){return this.S(qa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ua=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Va(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].U)return!0;return!1}
var Wa=(a,b)=>{if(void 0===h[a].T){var c=h[a];h[a]=function(...d){if(!h[a].T.hasOwnProperty(d.length))throw new I(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${h[a].T})!`);return h[a].T[d.length].apply(this,d)};h[a].T=[];h[a].T[c.oa]=c}},Xa=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].T&&void 0!==h[a].T[c])throw new I(`Cannot register public name '${a}' twice`);Wa(a,a);if(h[a].T.hasOwnProperty(c))throw new I(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].T[c]=b}else h[a]=b,h[a].oa=c},Ya=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(D[b+4*d>>2]);return c},Za=class extends Error{constructor(a){super(a);this.name="InternalError"}},$a=[],bb=(a,b)=>{a=F(a);var c;(c=$a[b])||($a[b]=c=ab.get(b));if("function"!=typeof c)throw new I(`unknown function pointer with signature ${a}: ${b}`);return c};class cb extends Error{}
var eb=a=>{a=db(a);var b=F(a);L(a);return b},fb=(a,b)=>{function c(f){e[f]||H[f]||(Ka[f]?Ka[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new cb(`${a}: `+d.map(eb).join([", "]));},gb=(a,b)=>{function c(k){k=b(k);if(k.length!==d.length)throw new Za("Mismatched type converter count");for(var q=0;q<d.length;++q)J(d[q],k[q])}var d=[];d.forEach(k=>Ka[k]=a);var e=Array(a.length),f=[],g=0;for(let [k,q]of a.entries())H.hasOwnProperty(q)?e[k]=H[q]:(f.push(q),G.hasOwnProperty(q)||(G[q]=
[]),G[q].push(()=>{e[k]=H[q];++g;g===f.length&&c(e)}));0===f.length&&c(e)},hb=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},N=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>
6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},O=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},ib=globalThis.TextDecoder&&new TextDecoder,jb=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},P=(a,b=0,c,d)=>{c=jb(a,b,c,d);if(16<c-b&&a.buffer&&ib)return ib.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;
e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},kb=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,lb=(a,b,c)=>{a>>=1;b=jb(y,a,b/2,c);if(16<b-a&&kb)return kb.decode(y.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(y[a]);return c},mb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)oa[b>>
1]=a.charCodeAt(e),b+=2;oa[b>>1]=0;return b-d},nb=a=>2*a.length,ob=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=D[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},pb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;C[b>>2]=f;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d},qb=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},rb=0,sb=[0,31,60,91,121,152,182,213,244,274,305,335],tb=[0,
31,59,90,120,151,181,212,243,273,304,334],Q={},ub=a=>{la=a;Ga||0<rb||(h.onExit?.(a),ka=!0);da(a,new Ba(a))},vb=a=>{if(!ka)try{if(a(),!(Ga||0<rb))try{la=a=la,ub(a)}catch(b){b instanceof Ba||"unwind"==b||da(1,b)}}catch(b){b instanceof Ba||"unwind"==b||da(1,b)}},wb=[],xb={},Bb=()=>{if(!Ab){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in xb)void 0===xb[b]?delete a[b]:
a[b]=xb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ab=c}return Ab},Ab,Cb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Db=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Cb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Eb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];
if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Fb=()=>{if(l){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Gb=a=>{(Gb=Fb())(a)},Hb=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Cb(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ib=[],Jb=[];
function Kb(a,b){Jb[a]={input:[],output:[],da:b};Lb(a,Mb)}
var Mb={open(a){var b=Jb[a.node.rdev];if(!b)throw new R(43);a.tty=b;a.seekable=!1},close(a){a.tty.da.fsync(a.tty)},fsync(a){a.tty.da.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.da.qa)throw new R(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.da.qa(a.tty)}catch(k){throw new R(29);}if(void 0===g&&0===e)throw new R(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.da.na)throw new R(60);try{for(var e=0;e<d;e++)a.tty.da.na(a.tty,b[c+e])}catch(f){throw new R(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Nb={qa(){a:{if(!Ib.length){var a=null;if(l){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(O(a)+1);a=N(a,b,0,b.length);b.length=a;Ib=b}a=Ib.shift()}return a},na(a,b){null===b||10===b?(ja(P(a.output)),a.output=
[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ja(P(a.output)),a.output=[])},Ia(){return{Da:25856,Fa:5,Ca:191,Ea:35387,Ba:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ja(){return 0},Ka(){return[24,80]}},Ob={na(a,b){null===b||10===b?(n(P(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(n(P(a.output)),a.output=[])}},S={W:null,Y(){return S.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new R(63);
S.W||(S.W={dir:{node:{$:S.O.$,X:S.O.X,lookup:S.O.lookup,ga:S.O.ga,rename:S.O.rename,unlink:S.O.unlink,rmdir:S.O.rmdir,readdir:S.O.readdir,symlink:S.O.symlink},stream:{V:S.P.V}},file:{node:{$:S.O.$,X:S.O.X},stream:{V:S.P.V,read:S.P.read,write:S.P.write,sa:S.P.sa,ua:S.P.ua}},link:{node:{$:S.O.$,X:S.O.X,readlink:S.O.readlink},stream:{}},pa:{node:{$:S.O.$,X:S.O.X},stream:Pb}});c=Qb(a,b,c,d);16384===(c.mode&61440)?(c.O=S.W.dir.node,c.P=S.W.dir.stream,c.N={}):32768===(c.mode&61440)?(c.O=S.W.file.node,c.P=
S.W.file.stream,c.R=0,c.N=null):40960===(c.mode&61440)?(c.O=S.W.link.node,c.P=S.W.link.stream):8192===(c.mode&61440)&&(c.O=S.W.pa.node,c.P=S.W.pa.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.N[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Ha(a){return a.N?a.N.subarray?a.N.subarray(0,a.R):new Uint8Array(a.N):new Uint8Array(0)},O:{$(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&
61440)?b.size=a.R:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},X(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.R!=b&&(0==b?(a.N=null,a.R=0):(c=a.N,a.N=new Uint8Array(b),c&&a.N.set(c.subarray(0,Math.min(b,a.R))),a.R=b)))},lookup(){S.ja||(S.ja=new R(44),S.ja.stack="<generic error, no stack>");throw S.ja;
},ga(a,b,c,d){return S.createNode(a,b,c,d)},rename(a,b,c){try{var d=Rb(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.N)throw new R(55);e=Sb(d.parent.id,d.name);if(T[e]===d)T[e]=d.ba;else for(e=T[e];e;){if(e.ba===d){e.ba=d.ba;break}e=e.ba}}delete a.parent.N[a.name];b.N[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.N[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=Rb(a,b),d;for(d in c.N)throw new R(55);delete a.N[b];a.ctime=a.mtime=Date.now()},
readdir(a){return[".","..",...Object.keys(a.N)]},symlink(a,b,c){a=S.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new R(28);return a.link}},P:{read(a,b,c,d,e){var f=a.node.N;if(e>=a.node.R)return 0;a=Math.min(a.node.R-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===t.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.N||a.N.subarray)){if(f)return a.N=
b.subarray(c,c+d),a.R=d;if(0===a.R&&0===e)return a.N=b.slice(c,c+d),a.R=d;if(e+d<=a.R)return a.N.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.N?a.N.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.N,a.N=new Uint8Array(f),0<a.R&&a.N.set(g.subarray(0,a.R),0));if(a.N.subarray&&b.subarray)a.N.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.N[e+f]=b[c+f];a.R=Math.max(a.R,e+d);return d},V(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.R);if(0>
b)throw new R(28);return b},sa(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new R(43);a=a.node.N;if(e&2||!a||a.buffer!==t.buffer){d=!0;wa();e=void 0;if(!e)throw new R(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);t.set(a,e)}}else d=!1,e=a.byteOffset;return{ia:e,Aa:d}},ua(a,b,c,d){S.P.write(a,b,0,d,c,!1);return 0}}},Tb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Ub=null,Vb={},U=[],Wb=1,T=null,Xb=!1,Yb=!0,Zb={},R=class{name="ErrnoError";constructor(a){this.ea=
a}},$b=class{fa={};node=null;get flags(){return this.fa.flags}set flags(a){this.fa.flags=a}get position(){return this.fa.position}set position(a){this.fa.position=a}},ac=class{O={};P={};ha=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Y=a.Y;this.id=Wb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=
-147}};
function V(a,b={}){if(!a)throw new R(44);b.la??(b.la=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=Ub,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Eb(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Db(e+"/"+a[f]);try{d=Rb(d,a[f])}catch(k){if(44===k?.ea&&g&&b.ya)return{path:e};throw k;}!d.ha||g&&!b.la||(d=d.ha.root);if(40960===(d.mode&61440)&&(!g||b.ka)){if(!d.O.readlink)throw new R(52);
d=d.O.readlink(d);"/"===d.charAt(0)||(d=Eb(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new R(32);}function Sb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%T.length}function Rb(a,b){var c=16384===(a.mode&61440)?(c=bc(a,"x"))?c:a.O.lookup?0:2:54;if(c)throw new R(c);for(c=T[Sb(a.id,b)];c;c=c.ba){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.O.lookup(a,b)}
function Qb(a,b,c,d){a=new ac(a,b,c,d);b=Sb(a.parent.id,a.name);a.ba=T[b];return T[b]=a}function cc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function bc(a,b){if(Yb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function dc(a,b){if(16384!==(a.mode&61440))return 54;try{return Rb(a,b),20}catch(c){}return bc(a,"wx")}function W(a){a=U[a];if(!a)throw new R(8);return a}
function ec(a,b){var c=null?.P.X,d=c?null:a;c??=a.O.X;if(!c)throw new R(63);c(d,b)}var Pb={open(a){a.P=Vb[a.node.rdev].P;a.P.open?.(a)},V(){throw new R(70);}};function Lb(a,b){Vb[a]={P:b}}function fc(a,b){var c="/"===b;if(c&&Ub)throw new R(10);if(!c&&b){var d=V(b,{la:!1});b=d.path;d=d.node;if(d.ha)throw new R(10);if(16384!==(d.mode&61440))throw new R(54);}b={type:a,La:{},ta:b,xa:[]};a=a.Y(b);a.Y=b;b.root=a;c?Ub=a:d&&(d.ha=b,d.Y&&d.Y.xa.push(b))}
function gc(a,b,c){var d=V(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new R(28);if("."===a||".."===a)throw new R(20);var e=dc(d,a);if(e)throw new R(e);if(!d.O.ga)throw new R(63);return d.O.ga(d,a,b,c)}function X(a){return gc(a,16895,0)}function hc(a,b,c){"undefined"==typeof c&&(c=b,b=438);gc(a,b|8192,c)}
function ic(a,b){if(!Hb(a))throw new R(44);var c=V(b,{parent:!0}).node;if(!c)throw new R(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=dc(c,b);if(d)throw new R(d);if(!c.O.symlink)throw new R(63);c.O.symlink(c,b,a)}
function jc(a,b){if(""===a)throw new R(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}c=b&64?33206:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");a=V(a,{ka:!(b&131072),ya:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new R(20);}else{if(e)throw new R(31);d=gc(a,c|511,0);f=!0}if(!d)throw new R(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&61440))throw new R(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==cc(b)||b&576)?31:bc(d,cc(b)):44))throw new R(e);if(b&512&&!f){e=d;e="string"==typeof e?V(e,{ka:!0}).node:e;if(16384===(e.mode&61440))throw new R(31);if(32768!==(e.mode&61440))throw new R(28);var g=bc(e,"w");if(g)throw new R(g);ec(e,{size:0,timestamp:Date.now()})}b&=-131713;a:for(e=d;;){if(e===e.parent){e=e.Y.ta;var k=k?"/"!==e[e.length-1]?`${e}/${k}`:e+k:e;break a}k=k?`${e.name}/${k}`:e.name;e=e.parent}k={node:d,path:k,flags:b,seekable:!0,
position:0,P:d.P,za:[],error:!1};e=-1;k=Object.assign(new $b,k);if(-1==e)a:{for(e=0;4096>=e;e++)if(!U[e])break a;throw new R(33);}k.fd=e;U[e]=k;k.P.open&&k.P.open(k);f&&(c&=511,d="string"==typeof d?V(d,{ka:!0}).node:d,ec(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),Ga:void 0}));!h.logReadFiles||b&1||a in Zb||(Zb[a]=1)}function kc(a,b,c){if(null===a.fd)throw new R(8);if(!a.seekable||!a.P.V)throw new R(70);if(0!=c&&1!=c&&2!=c)throw new R(28);a.position=a.P.V(a,b,c);a.za=[]}
function Y(a,b,c){a=Db("/dev/"+a);var d=Tb(!!b,!!c);Y.ra??(Y.ra=64);var e=Y.ra++<<8|0;Lb(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,k,q){for(var m=0,A=0;A<q;A++){try{var z=b()}catch(r){throw new R(29);}if(void 0===z&&0===m)throw new R(6);if(null===z||void 0===z)break;m++;g[k+A]=z}m&&(f.node.atime=Date.now());return m},write(f,g,k,q){for(var m=0;m<q;m++)try{c(g[k+m])}catch(A){throw new R(29);}q&&(f.node.mtime=f.node.ctime=Date.now());return m}});hc(a,d,e)}var lc={};T=Array(4096);
fc(S,"/");X("/tmp");X("/home");X("/home/web_user");(function(){X("/dev");Lb(259,{read:()=>0,write:(d,e,f,g)=>g,V:()=>0});hc("/dev/null",259);Kb(1280,Nb);Kb(1536,Ob);hc("/dev/tty",1280);hc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Gb(a),b=a.byteLength);return a[--b]};Y("random",c);Y("urandom",c);X("/dev/shm");X("/dev/shm/tmp")})();
(function(){X("/proc");var a=X("/proc/self");X("/proc/self/fd");fc({Y(){var b=Qb(a,"fd",16895,73);b.P={V:S.P.V};b.O={lookup(c,d){c=+d;var e=W(c);c={parent:null,Y:{ta:"fake"},O:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(U.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.noExitRuntime&&(Ga=h.noExitRuntime);h.print&&(ja=h.print);h.printErr&&(n=h.printErr);h.wasmBinary&&(p=h.wasmBinary);h.thisProgram&&(ca=h.thisProgram);
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();
var mc={37516:(a,b)=>{if(a=document.getElementById(a?P(u,a):""))a.textContent=b?P(u,b):""},37634:(a,b)=>{if(a=document.getElementById(a?P(u,a):""))a.innerHTML=b?P(u,b):""},37750:a=>{if((a=document.getElementById(a?P(u,a):""))&&void 0!==a.value){a=a.value;var b=O(a)+1,c=Z(b);N(a,u,c,b);return c}return 0},37995:(a,b)=>{(a=document.getElementById(a?P(u,a):""))&&void 0!==a.value&&(a.value=b?P(u,b):"")},38138:a=>{console.log(a?P(u,a):"")},38173:a=>{console.error(a?P(u,a):"")},38210:a=>{console.warn(a?
P(u,a):"")},38246:a=>{alert(a?P(u,a):"")},38275:(a,b)=>{a=prompt(a?P(u,a):"",b?P(u,b):"");if(null!==a){b=O(a)+1;var c=Z(b);N(a,u,c,b);return c}return 0},38474:a=>confirm(a?P(u,a):"")?1:0,38520:(a,b)=>{var c=document.getElementById("output");c&&(c.innerHTML='<canvas id="__canvas__" width="'+a+'" height="'+b+'" style="display:block; width:100%; height:auto; background:#111; border-radius:8px;"></canvas>')}},Z,L,db,nc,va,ab,oc={e:(a,b,c)=>{var d=new Ha(a);D[d.ia+16>>2]=0;D[d.ia+4>>2]=b;D[d.ia+8>>2]=
c;Ia=a;Ja++;throw Ia;},u:()=>wa(""),g:(a,b,c,d,e)=>{b=F(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=k=>BigInt.asUintN(g,k);e=f(e)}J(a,{name:b,S:f,Z:(g,k)=>{"number"==typeof k&&(k=BigInt(k));return k},aa:Oa(b,c,!d),U:null})},F:(a,b,c,d)=>{b=F(b);J(a,{name:b,S:function(e){return!!e},Z:function(e,f){return f?c:d},aa:function(e){return this.S(u[e])},U:null})},D:a=>J(a,Sa),f:(a,b,c)=>{b=F(b);J(a,{name:b,S:d=>d,Z:(d,e)=>e,aa:Ta(b,c),U:null})},h:(a,b,c,d,e,f,g)=>{var k=Ya(b,c);a=F(a);a=hb(a);e=bb(d,e);Xa(a,
function(){fb(`Cannot call ${a} due to unbound types`,k)},b-1);gb(k,q=>{var m=[q[0],null].concat(q.slice(1));q=a;var A=a;var z=e,r=m.length;if(2>r)throw new I("argTypes array size mismatch! Must at least get return value and 'this' types!");var B=null!==m[1]&&!1,E=Va(m),M=!m[0].wa,v=m[0],x=m[1];z=[A,Ma,z,f,Ua,v.S.bind(v),x?.Z.bind(x)];for(v=2;v<r;++v)x=m[v],z.push(x.Z.bind(x));if(!E)for(v=B?1:2;v<m.length;++v)null!==m[v].U&&z.push(m[v].U);E=Va(m);v=m.length-2;var w=[];x=["fn"];B&&x.push("thisWired");
for(r=0;r<v;++r)w.push(`arg${r}`),x.push(`arg${r}Wired`);w=w.join(",");x=x.join(",");w=`return function (${w}) {\n`;E&&(w+="var destructors = [];\n");var yb=E?"destructors":"null",La="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");B&&(w+=`var thisWired = toClassParamWire(${yb}, this);\n`);for(r=0;r<v;++r){var zb=`toArg${r}Wire`;w+=`var arg${r}Wired = ${zb}(${yb}, arg${r});\n`;La.push(zb)}w+=(M||g?"var rv = ":"")+`invoker(${x});\n`;if(E)w+="runDestructors(destructors);\n";
else for(r=B?1:2;r<m.length;++r)B=1===r?"thisWired":"arg"+(r-2)+"Wired",null!==m[r].U&&(w+=`${B}_dtor(${B});\n`,La.push(`${B}_dtor`));M&&(w+="var ret = fromRetWire(rv);\nreturn ret;\n");m=(new Function(La,w+"}\n"))(...z);A=Object.defineProperty(m,"name",{value:A});m=b-1;if(!h.hasOwnProperty(q))throw new Za("Replacing nonexistent public symbol");void 0!==h[q].T&&void 0!==m?h[q].T[m]=A:(h[q]=A,h[q].oa=m);return[]})},c:(a,b,c,d,e)=>{b=F(b);let f=k=>k;if(0===d){var g=32-8*c;f=k=>k<<g>>>g;e=f(e)}J(a,{name:b,
S:f,Z:(k,q)=>q,aa:Oa(b,c,0!==d),U:null})},a:(a,b,c)=>{function d(f){return new e(t.buffer,D[f+4>>2],D[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=F(c);J(a,{name:c,S:d,aa:d},{va:!0})},E:(a,b)=>{b=F(b);J(a,{name:b,S(c){var d=(d=c+4)?P(u,d,D[c>>2],!0):"";L(c);return d},Z(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new I("Cannot pass non-string to std::string");
var f=e?O(d):d.length;var g=Z(4+f+1),k=g+4;D[g>>2]=f;e?N(d,u,k,f+1):u.set(d,k);null!==c&&c.push(L,g);return g},aa:Ra,U(c){L(c)}})},d:(a,b,c)=>{c=F(c);if(2===b){var d=lb;var e=mb;var f=nb}else d=ob,e=pb,f=qb;J(a,{name:c,S:g=>{var k=d(g+4,D[g>>2]*b,!0);L(g);return k},Z:(g,k)=>{if("string"!=typeof k)throw new I(`Cannot pass non-string to C++ string type ${c}`);var q=f(k),m=Z(4+q+b);D[m>>2]=q/b;e(k,m+4,q+b);null!==g&&g.push(L,m);return m},aa:Ra,U(g){L(g)}})},i:(a,b)=>{b=F(b);J(a,{wa:!0,name:b,S:()=>{},
Z:()=>{}})},p:()=>{Ga=!1;rb=0},w:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);C[b>>2]=a.getSeconds();C[b+4>>2]=a.getMinutes();C[b+8>>2]=a.getHours();C[b+12>>2]=a.getDate();C[b+16>>2]=a.getMonth();C[b+20>>2]=a.getFullYear()-1900;C[b+24>>2]=a.getDay();var c=a.getFullYear();C[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?tb:sb)[a.getMonth()]+a.getDate()-1|0;C[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),
0,1)).getTimezoneOffset();C[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},r:(a,b)=>{Q[a]&&(clearTimeout(Q[a].id),delete Q[a]);if(!b)return 0;var c=setTimeout(()=>{delete Q[a];vb(()=>nc(a,performance.now()))},b);Q[a]={id:c,Ma:b};return 0},x:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();D[a>>2]=60*Math.max(f,e);C[b>>2]=Number(f!=e);b=g=>{var k=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(k/60)).padStart(2,
"0")}${String(k%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(N(a,u,c,17),N(b,u,d,17)):(N(a,u,d,17),N(b,u,c,17))},b:(a,b,c)=>{wb.length=0;for(var d;d=u[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;wb.push(112==d?D[c>>2]:106==d?ra[c>>3]:105==d?C[c>>2]:qa[c>>3]);c+=e?8:4}return mc[a](...wb)},C:()=>Date.now(),v:a=>{var b=u.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-va.buffer.byteLength+
65535)/65536|0;try{va.grow(d);ua();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},s:(a,b)=>{var c=0,d=0,e;for(e of Bb()){var f=b+c;D[a+d>>2]=f;c+=N(e,u,f,Infinity)+1;d+=4}return 0},t:(a,b)=>{var c=Bb();D[a>>2]=c.length;a=0;for(var d of c)a+=O(d)+1;D[b>>2]=a;return 0},z:function(a){try{var b=W(a);if(null===b.fd)throw new R(8);b.ma&&(b.ma=null);try{b.P.close&&b.P.close(b)}catch(c){throw c;}finally{U[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof lc||"ErrnoError"!==c.name)throw c;
return c.ea}},B:function(a,b,c,d){try{a:{var e=W(a);a=b;for(var f,g=b=0;g<c;g++){var k=D[a>>2],q=D[a+4>>2];a+=8;var m=e,A=k,z=q,r=f,B=t;if(0>z||0>r)throw new R(28);if(null===m.fd)throw new R(8);if(1===(m.flags&2097155))throw new R(8);if(16384===(m.node.mode&61440))throw new R(31);if(!m.P.read)throw new R(28);var E="undefined"!=typeof r;if(!E)r=m.position;else if(!m.seekable)throw new R(70);var M=m.P.read(m,B,A,z,r);E||(m.position+=M);var v=M;if(0>v){var x=-1;break a}b+=v;if(v<q)break;"undefined"!=
typeof f&&(f+=v)}x=b}D[d>>2]=x;return 0}catch(w){if("undefined"==typeof lc||"ErrnoError"!==w.name)throw w;return w.ea}},y:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=W(a);kc(e,b,c);ra[d>>3]=BigInt(e.position);e.ma&&0===b&&0===c&&(e.ma=null);return 0}catch(f){if("undefined"==typeof lc||"ErrnoError"!==f.name)throw f;return f.ea}},A:function(a,b,c,d){try{a:{var e=W(a);a=b;for(var f,g=b=0;g<c;g++){var k=D[a>>2],q=D[a+4>>2];a+=8;var m=e,A=k,
z=q,r=f,B=t;if(0>z||0>r)throw new R(28);if(null===m.fd)throw new R(8);if(0===(m.flags&2097155))throw new R(8);if(16384===(m.node.mode&61440))throw new R(31);if(!m.P.write)throw new R(28);m.seekable&&m.flags&1024&&kc(m,0,2);var E="undefined"!=typeof r;if(!E)r=m.position;else if(!m.seekable)throw new R(70);var M=m.P.write(m,B,A,z,r,void 0);E||(m.position+=M);var v=M;if(0>v){var x=-1;break a}b+=v;if(v<q)break;"undefined"!=typeof f&&(f+=v)}x=b}D[d>>2]=x;return 0}catch(w){if("undefined"==typeof lc||"ErrnoError"!==
w.name)throw w;return w.ea}},n:function(a){a=a?P(u,a):"";a=document.getElementById(a);if(!a)return 0;a.getContext("2d").clearRect(0,0,a.width,a.height);return 1},q:function(a,b,c){a=a?P(u,a):"";let d=document.getElementById(a);d||(d=document.createElement("canvas"),d.id=a,document.body.appendChild(d));d.width=b;d.height=c;return 1},l:function(a,b,c,d,e){a=a?P(u,a):"";a=document.getElementById(a);if(!a)return 0;a.getContext("2d").fillRect(b,c,d,e);return 1},j:function(a,b,c,d){a=a?P(u,a):"";b=b?P(u,
b):"";a=document.getElementById(a);if(!a)return 0;a.getContext("2d").fillText(b,c,d);return 1},m:function(a,b){a=a?P(u,a):"";b=b?P(u,b):"";a=document.getElementById(a);if(!a)return 0;a.getContext("2d").fillStyle=b;return 1},k:function(a,b){a=a?P(u,a):"";b=b?P(u,b):"";a=document.getElementById(a);if(!a)return 0;a.getContext("2d").font=b;return 1},o:ub},pc;
pc=await (async function(){function a(c){c=pc=c.exports;Z=c.I;L=c.J;db=c.K;nc=c.M;va=c.G;ab=c.L;ua();return pc}var b={a:oc};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});xa??=h.locateFile?h.locateFile("bulang.wasm",ea):ea+"bulang.wasm";return a((await Aa(b)).instance)}());
(function(){function a(){h.calledRun=!0;if(!ka){ta=!0;if(!h.noFSInit&&!Xb){var b,c;Xb=!0;b??=h.stdin;c??=h.stdout;d??=h.stderr;b?Y("stdin",b):ic("/dev/tty","/dev/stdin");c?Y("stdout",null,c):ic("/dev/tty","/dev/stdout");d?Y("stderr",null,d):ic("/dev/tty1","/dev/stderr");jc("/dev/stdin",0);jc("/dev/stdout",1);jc("/dev/stderr",1)}pc.H();Yb=!1;ma?.(h);h.onRuntimeInitialized?.();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var d=h.postRun.shift();Da.push(d)}Ca(Da)}}
if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Fa();Ca(Ea);h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);a()},1)):a()})();ta?moduleRtn=h:moduleRtn=new Promise((a,b)=>{ma=a;na=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=createBuLangModule;module.exports.default=createBuLangModule}else if(typeof define==="function"&&define["amd"])define([],()=>createBuLangModule);
