var createBuLangModule=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var h=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,l=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,ca="./this.program",n=(a,b)=>{throw b;};"undefined"!=typeof __filename?_scriptName=__filename:ba&&(_scriptName=self.location.href);var r="",da,ea;
if(l){var fs=require("fs");r=__dirname+"/";ea=a=>{a=fa(a)?new URL(a):a;return fs.readFileSync(a)};da=async a=>{a=fa(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);n=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{r=(new URL(".",_scriptName)).href}catch{}ba&&(ea=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});da=async a=>{if(fa(a))return new Promise((c,
d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ha=console.log.bind(console),x=console.error.bind(console),z,ia=!1,ja,fa=a=>a.startsWith("file://"),ka,la,B,C,ma,E,F,G,na,oa,pa,qa,ra=!1;
function sa(){var a=ta.buffer;B=new Int8Array(a);ma=new Int16Array(a);C=new Uint8Array(a);E=new Uint16Array(a);F=new Int32Array(a);G=new Uint32Array(a);na=new Float32Array(a);oa=new Float64Array(a);pa=new BigInt64Array(a);qa=new BigUint64Array(a)}function ua(a){h.onAbort?.(a);a="Aborted("+a+")";x(a);ia=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");la?.(a);throw a;}var va;
async function wa(a){if(!z)try{var b=await da(a);return new Uint8Array(b)}catch{}if(a==va&&z)a=new Uint8Array(z);else if(ea)a=ea(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){x(`failed to asynchronously prepare wasm: ${d}`),ua(d)}}
async function ya(a){var b=va;if(!z&&!fa(b)&&!l)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){x(`wasm streaming compile failed: ${d}`),x("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Aa=a=>{for(;0<a.length;)a.shift()(h)},Ba=[],Ca=[],Da=()=>{var a=h.preRun.shift();Ca.push(a)},Ea=!0;
class Fa{constructor(a){this.aa=a-24}}var Ga=0,Ha=0,H=a=>{for(var b="";;){var c=C[a++];if(!c)return b;b+=String.fromCharCode(c)}},I={},J={},Ia={},L=class extends Error{constructor(a){super(a);this.name="BindingError"}},Ka=a=>{throw new L(a);};
function La(a,b,c={}){var d=b.name;if(!a)throw new L(`type "${d}" must have a positive integer typeid pointer`);if(J.hasOwnProperty(a)){if(c.oa)return;throw new L(`Cannot register type '${d}' twice`);}J[a]=b;delete Ia[a];I.hasOwnProperty(a)&&(b=I[a],delete I[a],b.forEach(e=>e()))}function M(a,b,c={}){return La(a,b,c)}
var Ma=(a,b,c)=>{switch(b){case 1:return c?d=>B[d]:d=>C[d];case 2:return c?d=>ma[d>>1]:d=>E[d>>1];case 4:return c?d=>F[d>>2]:d=>G[d>>2];case 8:return c?d=>pa[d>>3]:d=>qa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Na=[],N=[0,1,,1,null,1,!0,1,!1,1],Oa=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Na.pop()||N.length;N[b]=a;N[b+1]=1;return b}};function Pa(a){return this.K(G[a>>2])}
var Qa={name:"emscripten::val",K:a=>{if(!a)throw new L(`Cannot use deleted val. handle = ${a}`);var b=N[a];9<a&&0===--N[a+1]&&(N[a]=void 0,Na.push(a));return b},S:(a,b)=>Oa(b),U:Pa,M:null},Ra=(a,b)=>{switch(b){case 4:return function(c){return this.K(na[c>>2])};case 8:return function(c){return this.K(oa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Sa=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Ta(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].M)return!0;return!1}
var Ua=(a,b)=>{if(void 0===h[a].L){var c=h[a];h[a]=function(...d){if(!h[a].L.hasOwnProperty(d.length))throw new L(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${h[a].L})!`);return h[a].L[d.length].apply(this,d)};h[a].L=[];h[a].L[c.ha]=c}},Va=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].L&&void 0!==h[a].L[c])throw new L(`Cannot register public name '${a}' twice`);Ua(a,a);if(h[a].L.hasOwnProperty(c))throw new L(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].L[c]=b}else h[a]=b,h[a].ha=c},Wa=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(G[b+4*d>>2]);return c},Xa=class extends Error{constructor(a){super(a);this.name="InternalError"}},Ya=[],$a=(a,b)=>{a=H(a);var c;(c=Ya[b])||(Ya[b]=c=Za.get(b));if("function"!=typeof c)throw new L(`unknown function pointer with signature ${a}: ${b}`);return c};class ab extends Error{}
var cb=a=>{a=bb(a);var b=H(a);O(a);return b},db=(a,b)=>{function c(f){e[f]||J[f]||(Ia[f]?Ia[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new ab(`${a}: `+d.map(cb).join([", "]));},eb=(a,b)=>{function c(k){k=b(k);if(k.length!==d.length)throw new Xa("Mismatched type converter count");for(var p=0;p<d.length;++p)M(d[p],k[p])}var d=[];d.forEach(k=>Ia[k]=a);var e=Array(a.length),f=[],g=0;for(let [k,p]of a.entries())J.hasOwnProperty(p)?e[k]=J[p]:(f.push(p),I.hasOwnProperty(p)||(I[p]=
[]),I[p].push(()=>{e[k]=J[p];++g;g===f.length&&c(e)}));0===f.length&&c(e)},fb=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},P=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>
6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},gb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},hb=globalThis.TextDecoder&&new TextDecoder,ib=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},Q=(a,b=0,c,d)=>{c=ib(a,b,c,d);if(16<c-b&&a.buffer&&hb)return hb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;
e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},jb=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,kb=(a,b,c)=>{a>>=1;b=ib(E,a,b/2,c);if(16<b-a&&jb)return jb.decode(E.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(E[a]);return c},lb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ma[b>>
1]=a.charCodeAt(e),b+=2;ma[b>>1]=0;return b-d},mb=a=>2*a.length,nb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=G[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},ob=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;F[b>>2]=f;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d},pb=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},qb=0,rb=[0,31,60,91,121,152,182,213,244,274,305,335],sb=[0,
31,59,90,120,151,181,212,243,273,304,334],R={},tb=a=>{ja=a;Ea||0<qb||(h.onExit?.(a),ia=!0);n(a,new za(a))},ub=a=>{if(!ia)try{if(a(),!(Ea||0<qb))try{ja=a=ja,tb(a)}catch(b){b instanceof za||"unwind"==b||n(1,b)}}catch(b){b instanceof za||"unwind"==b||n(1,b)}},vb={},zb=()=>{if(!wb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in vb)void 0===vb[b]?delete a[b]:a[b]=vb[b];
var c=[];for(b in a)c.push(`${b}=${a[b]}`);wb=c}return wb},wb,Ab=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Bb=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ab(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Cb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";
b&&=b.slice(0,-1);return a+b},Db=()=>{if(l){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Eb=a=>{(Eb=Db())(a)},Fb=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ab(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Gb=[],Hb=[];
function Ib(a,b){Hb[a]={input:[],output:[],W:b};Jb(a,Kb)}
var Kb={open(a){var b=Hb[a.node.rdev];if(!b)throw new S(43);a.tty=b;a.seekable=!1},close(a){a.tty.W.fsync(a.tty)},fsync(a){a.tty.W.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.W.ja)throw new S(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.W.ja(a.tty)}catch(k){throw new S(29);}if(void 0===g&&0===e)throw new S(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.W.ga)throw new S(60);try{for(var e=0;e<d;e++)a.tty.W.ga(a.tty,b[c+e])}catch(f){throw new S(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Lb={ja(){a:{if(!Gb.length){var a=null;if(l){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(gb(a)+1);a=P(a,b,0,b.length);b.length=a;Gb=b}a=Gb.shift()}return a},ga(a,b){null===b||10===b?(ha(Q(a.output)),a.output=
[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ha(Q(a.output)),a.output=[])},Ba(){return{wa:25856,ya:5,va:191,xa:35387,ua:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ca(){return 0},Da(){return[24,80]}},Mb={ga(a,b){null===b||10===b?(x(Q(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(x(Q(a.output)),a.output=[])}},T={O:null,R(){return T.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new S(63);
T.O||(T.O={dir:{node:{T:T.H.T,P:T.H.P,lookup:T.H.lookup,Z:T.H.Z,rename:T.H.rename,unlink:T.H.unlink,rmdir:T.H.rmdir,readdir:T.H.readdir,symlink:T.H.symlink},stream:{N:T.I.N}},file:{node:{T:T.H.T,P:T.H.P},stream:{N:T.I.N,read:T.I.read,write:T.I.write,la:T.I.la,na:T.I.na}},link:{node:{T:T.H.T,P:T.H.P,readlink:T.H.readlink},stream:{}},ia:{node:{T:T.H.T,P:T.H.P},stream:Nb}});c=Ob(a,b,c,d);16384===(c.mode&61440)?(c.H=T.O.dir.node,c.I=T.O.dir.stream,c.G={}):32768===(c.mode&61440)?(c.H=T.O.file.node,c.I=
T.O.file.stream,c.J=0,c.G=null):40960===(c.mode&61440)?(c.H=T.O.link.node,c.I=T.O.link.stream):8192===(c.mode&61440)&&(c.H=T.O.ia.node,c.I=T.O.ia.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.G[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Aa(a){return a.G?a.G.subarray?a.G.subarray(0,a.J):new Uint8Array(a.G):new Uint8Array(0)},H:{T(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&
61440)?b.size=a.J:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},P(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.J!=b&&(0==b?(a.G=null,a.J=0):(c=a.G,a.G=new Uint8Array(b),c&&a.G.set(c.subarray(0,Math.min(b,a.J))),a.J=b)))},lookup(){T.ba||(T.ba=new S(44),T.ba.stack="<generic error, no stack>");throw T.ba;
},Z(a,b,c,d){return T.createNode(a,b,c,d)},rename(a,b,c){try{var d=Pb(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.G)throw new S(55);e=Qb(d.parent.id,d.name);if(U[e]===d)U[e]=d.V;else for(e=U[e];e;){if(e.V===d){e.V=d.V;break}e=e.V}}delete a.parent.G[a.name];b.G[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.G[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=Pb(a,b),d;for(d in c.G)throw new S(55);delete a.G[b];a.ctime=a.mtime=Date.now()},
readdir(a){return[".","..",...Object.keys(a.G)]},symlink(a,b,c){a=T.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new S(28);return a.link}},I:{read(a,b,c,d,e){var f=a.node.G;if(e>=a.node.J)return 0;a=Math.min(a.node.J-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===B.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.G||a.G.subarray)){if(f)return a.G=
b.subarray(c,c+d),a.J=d;if(0===a.J&&0===e)return a.G=b.slice(c,c+d),a.J=d;if(e+d<=a.J)return a.G.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.G?a.G.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.G,a.G=new Uint8Array(f),0<a.J&&a.G.set(g.subarray(0,a.J),0));if(a.G.subarray&&b.subarray)a.G.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.G[e+f]=b[c+f];a.J=Math.max(a.J,e+d);return d},N(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.J);if(0>
b)throw new S(28);return b},la(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new S(43);a=a.node.G;if(e&2||!a||a.buffer!==B.buffer){d=!0;ua();e=void 0;if(!e)throw new S(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);B.set(a,e)}}else d=!1,e=a.byteOffset;return{aa:e,ta:d}},na(a,b,c,d){T.I.write(a,b,0,d,c,!1);return 0}}},Rb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Sb=null,Tb={},V=[],Ub=1,U=null,Vb=!1,Wb=!0,Xb={},S=class{name="ErrnoError";constructor(a){this.X=
a}},Yb=class{Y={};node=null;get flags(){return this.Y.flags}set flags(a){this.Y.flags=a}get position(){return this.Y.position}set position(a){this.Y.position=a}},Zb=class{H={};I={};$=null;constructor(a,b,c,d){a||=this;this.parent=a;this.R=a.R;this.id=Ub++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=
-147}};
function W(a,b={}){if(!a)throw new S(44);b.ea??(b.ea=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=Sb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Cb(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Bb(e+"/"+a[f]);try{d=Pb(d,a[f])}catch(k){if(44===k?.X&&g&&b.ra)return{path:e};throw k;}!d.$||g&&!b.ea||(d=d.$.root);if(40960===(d.mode&61440)&&(!g||b.da)){if(!d.H.readlink)throw new S(52);
d=d.H.readlink(d);"/"===d.charAt(0)||(d=Cb(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new S(32);}function Qb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%U.length}function Pb(a,b){var c=16384===(a.mode&61440)?(c=$b(a,"x"))?c:a.H.lookup?0:2:54;if(c)throw new S(c);for(c=U[Qb(a.id,b)];c;c=c.V){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.H.lookup(a,b)}
function Ob(a,b,c,d){a=new Zb(a,b,c,d);b=Qb(a.parent.id,a.name);a.V=U[b];return U[b]=a}function ac(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function $b(a,b){if(Wb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function bc(a,b){if(16384!==(a.mode&61440))return 54;try{return Pb(a,b),20}catch(c){}return $b(a,"wx")}function X(a){a=V[a];if(!a)throw new S(8);return a}
function cc(a,b){var c=null?.I.P,d=c?null:a;c??=a.H.P;if(!c)throw new S(63);c(d,b)}var Nb={open(a){a.I=Tb[a.node.rdev].I;a.I.open?.(a)},N(){throw new S(70);}};function Jb(a,b){Tb[a]={I:b}}function dc(a,b){var c="/"===b;if(c&&Sb)throw new S(10);if(!c&&b){var d=W(b,{ea:!1});b=d.path;d=d.node;if(d.$)throw new S(10);if(16384!==(d.mode&61440))throw new S(54);}b={type:a,Ea:{},ma:b,qa:[]};a=a.R(b);a.R=b;b.root=a;c?Sb=a:d&&(d.$=b,d.R&&d.R.qa.push(b))}
function ec(a,b,c){var d=W(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new S(28);if("."===a||".."===a)throw new S(20);var e=bc(d,a);if(e)throw new S(e);if(!d.H.Z)throw new S(63);return d.H.Z(d,a,b,c)}function Y(a){return ec(a,16895,0)}function fc(a,b,c){"undefined"==typeof c&&(c=b,b=438);ec(a,b|8192,c)}
function gc(a,b){if(!Fb(a))throw new S(44);var c=W(b,{parent:!0}).node;if(!c)throw new S(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=bc(c,b);if(d)throw new S(d);if(!c.H.symlink)throw new S(63);c.H.symlink(c,b,a)}
function hc(a,b){if(""===a)throw new S(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}c=b&64?33206:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");a=W(a,{da:!(b&131072),ra:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new S(20);}else{if(e)throw new S(31);d=ec(a,c|511,0);f=!0}if(!d)throw new S(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&61440))throw new S(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==ac(b)||b&576)?31:$b(d,ac(b)):44))throw new S(e);if(b&512&&!f){e=d;e="string"==typeof e?W(e,{da:!0}).node:e;if(16384===(e.mode&61440))throw new S(31);if(32768!==(e.mode&61440))throw new S(28);var g=$b(e,"w");if(g)throw new S(g);cc(e,{size:0,timestamp:Date.now()})}b&=-131713;a:for(e=d;;){if(e===e.parent){e=e.R.ma;var k=k?"/"!==e[e.length-1]?`${e}/${k}`:e+k:e;break a}k=k?`${e.name}/${k}`:e.name;e=e.parent}k={node:d,path:k,flags:b,seekable:!0,
position:0,I:d.I,sa:[],error:!1};e=-1;k=Object.assign(new Yb,k);if(-1==e)a:{for(e=0;4096>=e;e++)if(!V[e])break a;throw new S(33);}k.fd=e;V[e]=k;k.I.open&&k.I.open(k);f&&(c&=511,d="string"==typeof d?W(d,{da:!0}).node:d,cc(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),za:void 0}));!h.logReadFiles||b&1||a in Xb||(Xb[a]=1)}function ic(a,b,c){if(null===a.fd)throw new S(8);if(!a.seekable||!a.I.N)throw new S(70);if(0!=c&&1!=c&&2!=c)throw new S(28);a.position=a.I.N(a,b,c);a.sa=[]}
function Z(a,b,c){a=Bb("/dev/"+a);var d=Rb(!!b,!!c);Z.ka??(Z.ka=64);var e=Z.ka++<<8|0;Jb(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,k,p){for(var m=0,y=0;y<p;y++){try{var w=b()}catch(q){throw new S(29);}if(void 0===w&&0===m)throw new S(6);if(null===w||void 0===w)break;m++;g[k+y]=w}m&&(f.node.atime=Date.now());return m},write(f,g,k,p){for(var m=0;m<p;m++)try{c(g[k+m])}catch(y){throw new S(29);}p&&(f.node.mtime=f.node.ctime=Date.now());return m}});fc(a,d,e)}var jc={};U=Array(4096);
dc(T,"/");Y("/tmp");Y("/home");Y("/home/web_user");(function(){Y("/dev");Jb(259,{read:()=>0,write:(d,e,f,g)=>g,N:()=>0});fc("/dev/null",259);Ib(1280,Lb);Ib(1536,Mb);fc("/dev/tty",1280);fc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Eb(a),b=a.byteLength);return a[--b]};Z("random",c);Z("urandom",c);Y("/dev/shm");Y("/dev/shm/tmp")})();
(function(){Y("/proc");var a=Y("/proc/self");Y("/proc/self/fd");dc({R(){var b=Ob(a,"fd",16895,73);b.I={N:T.I.N};b.H={lookup(c,d){c=+d;var e=X(c);c={parent:null,R:{ma:"fake"},H:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(V.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.noExitRuntime&&(Ea=h.noExitRuntime);h.print&&(ha=h.print);h.printErr&&(x=h.printErr);h.wasmBinary&&(z=h.wasmBinary);h.thisProgram&&(ca=h.thisProgram);
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();
var kc,O,bb,lc,ta,Za,mc={d:(a,b,c)=>{var d=new Fa(a);G[d.aa+16>>2]=0;G[d.aa+4>>2]=b;G[d.aa+8>>2]=c;Ga=a;Ha++;throw Ga;},q:()=>ua(""),f:(a,b,c,d,e)=>{b=H(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=k=>BigInt.asUintN(g,k);e=f(e)}M(a,{name:b,K:f,S:(g,k)=>{"number"==typeof k&&(k=BigInt(k));return k},U:Ma(b,c,!d),M:null})},j:(a,b,c,d)=>{b=H(b);M(a,{name:b,K:function(e){return!!e},S:function(e,f){return f?c:d},U:function(e){return this.K(C[e])},M:null})},h:a=>M(a,Qa),e:(a,b,c)=>{b=H(b);M(a,{name:b,K:d=>
d,S:(d,e)=>e,U:Ra(b,c),M:null})},g:(a,b,c,d,e,f,g)=>{var k=Wa(b,c);a=H(a);a=fb(a);e=$a(d,e);Va(a,function(){db(`Cannot call ${a} due to unbound types`,k)},b-1);eb(k,p=>{var m=[p[0],null].concat(p.slice(1));p=a;var y=a;var w=e,q=m.length;if(2>q)throw new L("argTypes array size mismatch! Must at least get return value and 'this' types!");var A=null!==m[1]&&!1,D=Ta(m),K=!m[0].pa,t=m[0],v=m[1];w=[y,Ka,w,f,Sa,t.K.bind(t),v?.S.bind(v)];for(t=2;t<q;++t)v=m[t],w.push(v.S.bind(v));if(!D)for(t=A?1:2;t<m.length;++t)null!==
m[t].M&&w.push(m[t].M);D=Ta(m);t=m.length-2;var u=[];v=["fn"];A&&v.push("thisWired");for(q=0;q<t;++q)u.push(`arg${q}`),v.push(`arg${q}Wired`);u=u.join(",");v=v.join(",");u=`return function (${u}) {\n`;D&&(u+="var destructors = [];\n");var xb=D?"destructors":"null",Ja="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");A&&(u+=`var thisWired = toClassParamWire(${xb}, this);\n`);for(q=0;q<t;++q){var yb=`toArg${q}Wire`;u+=`var arg${q}Wired = ${yb}(${xb}, arg${q});\n`;
Ja.push(yb)}u+=(K||g?"var rv = ":"")+`invoker(${v});\n`;if(D)u+="runDestructors(destructors);\n";else for(q=A?1:2;q<m.length;++q)A=1===q?"thisWired":"arg"+(q-2)+"Wired",null!==m[q].M&&(u+=`${A}_dtor(${A});\n`,Ja.push(`${A}_dtor`));K&&(u+="var ret = fromRetWire(rv);\nreturn ret;\n");m=(new Function(Ja,u+"}\n"))(...w);y=Object.defineProperty(m,"name",{value:y});m=b-1;if(!h.hasOwnProperty(p))throw new Xa("Replacing nonexistent public symbol");void 0!==h[p].L&&void 0!==m?h[p].L[m]=y:(h[p]=y,h[p].ha=m);
return[]})},b:(a,b,c,d,e)=>{b=H(b);let f=k=>k;if(0===d){var g=32-8*c;f=k=>k<<g>>>g;e=f(e)}M(a,{name:b,K:f,S:(k,p)=>p,U:Ma(b,c,0!==d),M:null})},a:(a,b,c)=>{function d(f){return new e(B.buffer,G[f+4>>2],G[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=H(c);M(a,{name:c,K:d,U:d},{oa:!0})},i:(a,b)=>{b=H(b);M(a,{name:b,K(c){var d=(d=c+4)?Q(C,d,G[c>>2],!0):"";O(c);return d},S(c,d){d instanceof ArrayBuffer&&(d=
new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new L("Cannot pass non-string to std::string");var f=e?gb(d):d.length;var g=kc(4+f+1),k=g+4;G[g>>2]=f;e?P(d,C,k,f+1):C.set(d,k);null!==c&&c.push(O,g);return g},U:Pa,M(c){O(c)}})},c:(a,b,c)=>{c=H(c);if(2===b){var d=kb;var e=lb;var f=mb}else d=nb,e=ob,f=pb;M(a,{name:c,K:g=>{var k=d(g+4,G[g>>2]*b,!0);O(g);return k},S:(g,k)=>{if("string"!=typeof k)throw new L(`Cannot pass non-string to C++ string type ${c}`);
var p=f(k),m=kc(4+p+b);G[m>>2]=p/b;e(k,m+4,p+b);null!==g&&g.push(O,m);return m},U:Pa,M(g){O(g)}})},p:(a,b)=>{b=H(b);M(a,{pa:!0,name:b,K:()=>{},S:()=>{}})},l:()=>{Ea=!1;qb=0},s:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);F[b>>2]=a.getSeconds();F[b+4>>2]=a.getMinutes();F[b+8>>2]=a.getHours();F[b+12>>2]=a.getDate();F[b+16>>2]=a.getMonth();F[b+20>>2]=a.getFullYear()-1900;F[b+24>>2]=a.getDay();var c=a.getFullYear();F[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?sb:
rb)[a.getMonth()]+a.getDate()-1|0;F[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();F[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},m:(a,b)=>{R[a]&&(clearTimeout(R[a].id),delete R[a]);if(!b)return 0;var c=setTimeout(()=>{delete R[a];ub(()=>lc(a,performance.now()))},b);R[a]={id:c,Fa:b};return 0},t:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,
6,1)).getTimezoneOffset();G[a>>2]=60*Math.max(f,e);F[b>>2]=Number(f!=e);b=g=>{var k=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(P(a,C,c,17),P(b,C,d,17)):(P(a,C,d,17),P(b,C,c,17))},y:()=>Date.now(),r:a=>{var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ta.buffer.byteLength+65535)/65536|
0;try{ta.grow(d);sa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},n:(a,b)=>{var c=0,d=0,e;for(e of zb()){var f=b+c;G[a+d>>2]=f;c+=P(e,C,f,Infinity)+1;d+=4}return 0},o:(a,b)=>{var c=zb();G[a>>2]=c.length;a=0;for(var d of c)a+=gb(d)+1;G[b>>2]=a;return 0},v:function(a){try{var b=X(a);if(null===b.fd)throw new S(8);b.fa&&(b.fa=null);try{b.I.close&&b.I.close(b)}catch(c){throw c;}finally{V[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof jc||"ErrnoError"!==c.name)throw c;return c.X}},
x:function(a,b,c,d){try{a:{var e=X(a);a=b;for(var f,g=b=0;g<c;g++){var k=G[a>>2],p=G[a+4>>2];a+=8;var m=e,y=k,w=p,q=f,A=B;if(0>w||0>q)throw new S(28);if(null===m.fd)throw new S(8);if(1===(m.flags&2097155))throw new S(8);if(16384===(m.node.mode&61440))throw new S(31);if(!m.I.read)throw new S(28);var D="undefined"!=typeof q;if(!D)q=m.position;else if(!m.seekable)throw new S(70);var K=m.I.read(m,A,y,w,q);D||(m.position+=K);var t=K;if(0>t){var v=-1;break a}b+=t;if(t<p)break;"undefined"!=typeof f&&(f+=
t)}v=b}G[d>>2]=v;return 0}catch(u){if("undefined"==typeof jc||"ErrnoError"!==u.name)throw u;return u.X}},u:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=X(a);ic(e,b,c);pa[d>>3]=BigInt(e.position);e.fa&&0===b&&0===c&&(e.fa=null);return 0}catch(f){if("undefined"==typeof jc||"ErrnoError"!==f.name)throw f;return f.X}},w:function(a,b,c,d){try{a:{var e=X(a);a=b;for(var f,g=b=0;g<c;g++){var k=G[a>>2],p=G[a+4>>2];a+=8;var m=e,y=k,w=p,q=f,A=B;if(0>
w||0>q)throw new S(28);if(null===m.fd)throw new S(8);if(0===(m.flags&2097155))throw new S(8);if(16384===(m.node.mode&61440))throw new S(31);if(!m.I.write)throw new S(28);m.seekable&&m.flags&1024&&ic(m,0,2);var D="undefined"!=typeof q;if(!D)q=m.position;else if(!m.seekable)throw new S(70);var K=m.I.write(m,A,y,w,q,void 0);D||(m.position+=K);var t=K;if(0>t){var v=-1;break a}b+=t;if(t<p)break;"undefined"!=typeof f&&(f+=t)}v=b}G[d>>2]=v;return 0}catch(u){if("undefined"==typeof jc||"ErrnoError"!==u.name)throw u;
return u.X}},k:tb},nc;nc=await (async function(){function a(c){c=nc=c.exports;kc=c.B;O=c.C;bb=c.D;lc=c.F;ta=c.z;Za=c.E;sa();return nc}var b={a:mc};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});va??=h.locateFile?h.locateFile("bulang.wasm",r):r+"bulang.wasm";return a((await ya(b)).instance)}());
(function(){function a(){h.calledRun=!0;if(!ia){ra=!0;if(!h.noFSInit&&!Vb){var b,c;Vb=!0;b??=h.stdin;c??=h.stdout;d??=h.stderr;b?Z("stdin",b):gc("/dev/tty","/dev/stdin");c?Z("stdout",null,c):gc("/dev/tty","/dev/stdout");d?Z("stderr",null,d):gc("/dev/tty1","/dev/stderr");hc("/dev/stdin",0);hc("/dev/stdout",1);hc("/dev/stderr",1)}nc.A();Wb=!1;ka?.(h);h.onRuntimeInitialized?.();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var d=h.postRun.shift();Ba.push(d)}Aa(Ba)}}
if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Da();Aa(Ca);h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);a()},1)):a()})();ra?moduleRtn=h:moduleRtn=new Promise((a,b)=>{ka=a;la=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=createBuLangModule;module.exports.default=createBuLangModule}else if(typeof define==="function"&&define["amd"])define([],()=>createBuLangModule);
